<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>
<?php echo $this->renderTabs($this->tabs); ?>


<style>
    .update-log {
        background: hsl(225, 6.1%, 12.9%);
        padding: 15px;
        overflow-y:scroll;
        max-height: 600px;
    }
    .update-log-message {
        margin-bottom:10px;
        color: hsl(80.6, 75.5%, 58.4%);
    }
</style>

<script>

    var $j = jQuery.noConflict();
    $j(document).ready(function() {
        startUpdating();
    });

    function runUpdatingTask() {
        $j.get('/modules/microweber/index.php/update/queue', function (data) {

        });
    }

    function startUpdating() {
        $j.get('/modules/microweber/index.php/update/start', function(data) {

            $j.each(data.messages, function(iMessage, messageData) {
                setTimeout(function() {
                    var html = '<div class="update-log-message">' +
                        '            <span class="pul-icon pul-icon--intent pul-icon--success pul-icon--on-dark">' +
                        '                <svg focusable="false"><use href="/ui-library/images/symbols.svg?6bd5879cb9a032639fb375ff6f1dcd26#check-mark-circle-filled:16"></use></svg>' +
                        '            </span>' +
                        ' ' + messageData['message'] +
                        '    </div>';
                    $j('.update-log').append(html);

                    $j(".update-log").animate({
                        scrollTop: $j('.update-log')[0].scrollHeight
                    }, 50);

                    if (messageData['next']) {
                        runUpdatingTask();
                    }

                }, iMessage * 600);

            });

        });
    }
</script>

<div class="update-log">

    <div class="update-log-message">
            <span class="pul-icon pul-icon--intent pul-icon--success pul-icon--on-dark">
                <svg focusable="false"><use href="/ui-library/images/symbols.svg?6bd5879cb9a032639fb375ff6f1dcd26#check-mark-circle-filled:16"></use></svg>
            </span>
        Starting update
    </div>

</div>