<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>
<?php echo $this->renderTabs($this->tabs); ?>


<style>
    .update-log {
        background: hsl(225, 6.1%, 12.9%);
        padding: 15px;
    }
    .update-log-message {
        color: hsl(80.6, 75.5%, 58.4%);
    }
</style>

<div class="update-log">

    <div class="update-log-message">
            <span class="pul-icon pul-icon--intent pul-icon--success pul-icon--on-dark">
                <svg focusable="false"><use href="/ui-library/images/symbols.svg?6bd5879cb9a032639fb375ff6f1dcd26#check-mark-circle-filled:16"></use></svg>
            </span>
        Starting update
    </div>

</div>