<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<style>
    .update-log {
        overflow-y:scroll;
        max-height: 500px;
        padding: 15px;
        background: hsl(0, 0%, 97%);
        display: none;
    }
    .update-log-message {
        margin-bottom: 10px;
        color: #2d3a47;
    }
    .update-log-message.error {
        color: #d02d4b;
    }
</style>

<script>

    var $j = jQuery.noConflict();
    $j(document).ready(function() {
        $j('.js-start-update-button').on('click', function() {
            startUpdating();
        });
    });

    function runUpdatingTask() {
        $j.get('/modules/microweber/index.php/update/queue', function (data) {
            setTimeout(function () {
                showBackToPluginBtn();
            }, 10000);
        });
    }

    function showBackToPluginBtn() {
        $j('.js-back-to-plugin').html('<br />You can go back to plugin<br /><a href="<?php echo $this->mainPluginLink; ?>" class="btn btn-info i-link">Back to plugin</a>');
    }

    function startUpdating() {
        $j('.update-action').hide();
        $j('.update-log').show();
        $j.get('/modules/microweber/index.php/update/start', function(data) {

            $j.each(data.messages, function(iMessage, messageData) {
                setTimeout(function() {

                    var html = '';
                    if (messageData['error']) {

                        showBackToPluginBtn();

                        html = '<div class="update-log-message error">' +
                            '' +
                            ' ' + messageData['message'] +
                            '</div>';
                        $j('.update-log').append(html);

                    } else {
                        html = '<div class="update-log-message">' +
                            '            ' +
                            ' ' + messageData['message'] +
                            '    </div>';

                        $j('.update-log').append(html);
                    }

                    if (messageData['next']) {

                        runUpdatingTask();

                        html = '<div class="update-log-message">' +
                            '     <span class="pul-icon pul-icon--intent pul-icon--success pul-icon--on-dark">' +
                            '        <img src="<?php echo pm_Context::getBaseUrl() . 'images/loading.gif';?>" />' +
                            '     </span>' +
                            ' Update task running...' +
                            '  </div>';

                        $j('.update-log').append(html);
                    }

                    $j(".update-log").animate({
                        scrollTop: $j('.update-log')[0].scrollHeight
                    }, 50);

                }, iMessage * 600);

            });

        });
    }
</script>

<div class="update-action">
    <h3 style="margin-top:20px">
        Are you sure you want to start the update?
    </h3>
    <button class="pul-button js-start-update-button" type="button">
        <span>YES, START UPDATE</span>
    </button>
</div>

<div class="update-log">

    <div class="update-log-message">
        Starting update
    </div>

</div>

<div class="js-back-to-plugin"></div>
