<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<?php echo $this->renderTabs($this->tabs); ?>

<div class="pul-card pul-card--extended">
    <div class="pul-card__inner">
        <div class="pul-card__body">
            <div class="pul-card__main">
                <div class="pul-card__main-content">
                    <div class="js-step-<?php echo $this->currentStep;?>">
                        <h3>PHP Upgrade Wizard - Step <?php echo $this->currentStep;?> of <?php echo $this->maxSteps;?></h3>


                        <div class="pul-extended-status-message__container">
                            <div class="pul-extended-status-message pul-extended-status-message--success" style="max-width: 100%;">
                                <div class="pul-extended-status-message__image">
                                    <img src="<?php echo pm_Context::getBaseUrl();?>images/extended-status-message-icon.png" alt="">
                                </div>
                                <div class="pul-extended-status-message__body">
                                    <h3 class="pul-heading pul-heading--h3 pul-extended-status-message__title">
                                        Upgrading process of <?php echo Modules_Microweber_WhiteLabel::getBrandName(); ?> is finished!
                                    </h3>
                                    <div class="pul-extended-status-message__description">
                                        Now you can use <?php echo $this->latestAppVersion; ?> version of app.
                                    </div>
                                    <div class="pul-extended-status-message__actions">
                                        <a href="<?php echo $this->moduleUpdateLink; ?>" class="pul-button pul-button--primary">
                                            <span class="pul-button__inner">
                                                <span>Back to  <?php echo Modules_Microweber_WhiteLabel::getBrandName(); ?> module</span>
                                            </span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
