<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<?php echo $this->renderTabs($this->tabs); ?>

<div class="pul-card pul-card--extended">
    <div class="pul-card__inner">
        <div class="pul-card__body">
            <div class="pul-card__main">
                <div class="pul-card__main-content">
                    <div class="js-step-<?php echo $this->currentStep;?>">
                        <h3>PHP Upgrade Wizard - Step <?php echo $this->currentStep;?>/<?php echo $this->maxSteps;?></h3>

                        <p>
                            Some of your websites are on old version of PHP. <br />
                            The outdated websites must be upgraded to be compatible with the next version of <?php echo $this->moduleName; ?>.
                        </p>
                        <div class="js-show-outdated-domains">
                            <div class="pul-content-loader" style="max-width: 250px">
                                <div class="pul-content-loader__container">
                                    <div class="pul-content-loader__loader pul-content-loader__loader--spinner">
                                        <svg class="pul-spinner pul-content-loader__indicator" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
                                            <circle class="pul-spinner__path" fill="none" stroke-width="6" stroke-linecap="round" cx="24" cy="24" r="21"></circle>
                                        </svg>
                                        <div class="pul-content-loader__text">Loading outdated websites...</div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <br />
                        <div class="js-messages" style="padding-left:15px;margin-top:20px;"></div>
                        <br />
                        <button class="btn btn-primary js-upgrade-websites" style="display: none">Upgrade websites</button>
                        <a href="<?php echo $this->nextStepLink; ?>" class="btn btn-primary js-next-step" style="display: none">Next Step</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
