<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<?php echo $this->renderTabs($this->tabs); ?>

<div class="pul-card pul-card--extended">
    <div class="pul-card__inner">
        <div class="pul-card__body">
            <div class="pul-card__main">
                <div class="pul-card__main-content">
                    <div class="js-step-<?php echo $this->currentStep;?>">
                        <h3>PHP Upgrade Wizard - Step <?php echo $this->currentStep;?>/<?php echo $this->maxSteps;?></h3>


                        <p>
                            To install fresh new websites of <b><?php echo Modules_Microweber_WhiteLabel::getBrandName(); ?> <?php echo $this->latestAppVersion; ?></b>
                            your <b>hosting plans</b> must support <b>PHP <?php echo $this->requiredPhpVersion; ?></b>. <br />
                            We will check information about this right now.
                        </p>

                        <div class="js-check-hosting-plans-support-php-version">
                            <div class="pul-content-loader" style="max-width: 450px">
                                <div class="pul-content-loader__container">
                                    <div class="pul-content-loader__loader pul-content-loader__loader--spinner">
                                        <svg class="pul-spinner pul-content-loader__indicator" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
                                            <circle class="pul-spinner__path" fill="none" stroke-width="6" stroke-linecap="round" cx="24" cy="24" r="21"></circle>
                                        </svg>
                                        <div class="pul-content-loader__text">Checking supported php versions of hosting plans...</div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <button class="btn btn-primary js-upgrade-hosting-plans" style="display: none">Upgrade Hosting Plans</button>
                        <a href="<?php echo $this->nextStepLink; ?>" class="btn btn-primary js-next-step" style="display: none">Next step</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
