<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<?php echo $this->renderTabs($this->tabs); ?>

<div class="pul-card pul-card--extended">
    <div class="pul-card__inner">
        <div class="pul-card__body">
            <div class="pul-card__main">
                <div class="pul-card__main-content">
                    <div class="js-step-<?php echo $this->currentStep;?>">
                        <h3>PHP Upgrade Wizard - Step <?php echo $this->currentStep;?>/<?php echo $this->maxSteps;?></h3>

                        <p>
                            Welcome to PHP Upgrade Wizard! <br />
                            This tool will help you to upgrade your outdated websites quickly.
                        </p>
                        <a href="<?php echo $this->nextStepLink; ?>" class="btn btn-primary">Next step</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
