<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>


<div class="pul-card pul-card--extended">
    <div class="pul-card__inner">
        <div class="pul-card__body">
            <div class="pul-card__main">
                <div class="pul-card__main-content">
                    <div class="js-step-<?php echo $this->currentStep;?>">
                        <h3>Welcome to PHP Upgrade Wizard!</h3>
                        <p>
                            This tool will help you to upgrade your outdated websites quickly.
                        </p>
                        <a href="<?php echo $this->nextStepLink; ?>" class="btn btn-primary">Start Wizard</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
