<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>
<?php echo $this->renderTabs($this->tabs); ?>

<?php
if ($this->errorMessage):
    ?>
    <div class="msg-box msg-error">
        <div class="msg-content"><b>Error:</b>
            <?php echo $this->errorMessage; ?>
        </div>
    </div>
<?php endif; ?>

<?php if($this->limitations['app_installations_freeze']): ?>

<div class="microweber-license-message">
    <h2>You have reached your plan limit.</h2>
    <h3>Your plan limit: <?php echo $this->limitations['app_installations_limit']; ?> websites</h3>
    <h3>Active installations: <?php echo $this->limitations['app_installations_count']; ?> websites</h3>

    <br />
    <p><a href="<?php echo $this->buyLink; ?>" class="btn btn-info i-link" target="_blank">Upgrade you license</a>
    or
    <a href="<?php echo $this->newLicenseLink; ?>" class="btn btn-info i-link" >Install license key here</a>
    </p>
</div>
<?php endif; ?>

<?php
if ($this->list) {
    echo $this->renderList($this->list);
}
?>

<a href="<?php echo $this->refreshDomainLink; ?>" class="btn btn-info i-link">Refresh domains</a>
