<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>
<?php echo $this->renderTabs($this->tabs); ?>

<?php
if ($this->errorMessage):
    ?>
    <div class="msg-box msg-error">
        <div class="msg-content"><b>Error:</b>
            <?php echo $this->errorMessage; ?>
        </div>
    </div>
<?php endif; ?>

<?php echo $this->renderList($this->list); ?>

<a href="<?php echo $this->refreshDomainLink; ?>" class="btn btn-info i-link">Refresh domains</a>
