<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>
<?php echo $this->renderTabs($this->tabs); ?>

<?php
/*
if ($this->selinuxError):
?>
<div class="alert alert-danger">
    <i class="fa fa-times"></i> SELinux is enabled on your server and symliked installations will not work <br />
    <a onclick="confirmSelinux();">Click here to disable SELinux, so you can use symliked installations</a>
    <br />
    OR to disable SELinux manually follow this <a href="https://support.plesk.com/hc/en-us/articles/213947705-How-to-enable-disable-SELinux-on-a-server#:~:text=To%20temporary%20change%20SELinux%20mode,Commonly%20used%20for%20troubleshooting" target="_blank">guide</a>.
</div>

<script>
    function confirmSelinux() {
        if (confirm('Are you sure want to disable SELinux?')) {
            if (confirm('This will reboot your server, please confirm.')) {
                if (confirm('Reboot server can take more than 5 minutes, click ok to continue with server reboot.')) {
                    window.location.href = "<?php echo $this->activateSymlinking; ?>";
                }
            }
        }
    }
</script>
<?php
endif;
*/
?>

<h3>Choose installation options</h3>
<b>Random values will be generated if fields are left blank.</b>

<br />
<br />
<div class="js-microweber-install-form" style="display:none;">
<?php echo $this->form; ?>
</div>