<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<?php echo $this->renderTabs($this->tabs); ?>

<h3><?php echo $this->moduleName; ?> Plugin Version</h3>
<span>Your Plugin version is: </span> <b><?php echo $this->currentPluginVersion; ?></b> <br />
<span>Latest Plugin version is:</span> <b><?php echo $this->latestPluginVersion; ?></b> <br />
<span>Latest Plugin update date:</span> <b><?php echo $this->latestPluginUpdateDate; ?></b><br />

<?php if (version_compare($this->latestPluginVersion, $this->currentPluginVersion, '>')) : ?>
<div class="pul-alert pul-alert--info pul-status-message pul-status-message--info" style="line-height: 40px">
    New version of plugin is available.
    <br />
    <a href="<?php echo $this->updatePluginLink; ?>" class="pul-button pul-button--primary">
        <span class="pul-button__inner">
            <span>Update</span> 
        </span>
    </a>
</div>
<?php else: ?>
    <div class="pul-alert pul-alert--success pul-status-message pul-status-message--success">

        Your plugin is up-to-date!
    </div>
<?php endif; ?>