<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<h3>Download Last Version Of <?php echo Modules_Microweber_WhiteLabel::getBrandName(); ?></h3>

<span>Latest available version is </span> <b><?php echo $this->latestVersion; ?></b> <br />
<br />

<button data-update-link="<?php echo $this->updateLink; ?>" class="btn action js-check-for-update" style="width:300px;font-size:18px;padding: 15px;">
    Download Now
</button>