<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<h3>Download Last Version Of Microweber CMS</h3>

<span>Latest available version is </span> <b><?php echo $this->latestVersion; ?></b> <br />
<br />

<a href="<?php echo $this->updateLink; ?>" class="btn action" style="width:300px;font-size:18px;padding: 15px;">Download Now</a>