<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<?php echo $this->renderTabs($this->tabs); ?>

<h3><?php echo $this->moduleName; ?> version</h3>
<span>Your version is: </span> <b><?php echo $this->currentVersion; ?></b> <br />
<span>Latest version is:</span> <b><?php echo $this->latestVersion; ?></b> <br />
<span>Latest download date:</span> <b><?php echo $this->latestDownloadDate; ?></b><br />
<br />

<?php if ($this->availableTemplates): ?>
    <h3>Available Templates (<?php echo count($this->availableTemplates); ?>)</h3>
    <?php foreach ($this->availableTemplates as $template): ?>
        <?php echo $template['name']; ?><?php if ($template['version']): ?>(<?php echo $template['version']; ?>)
        <?php endif; ?>, &nbsp;

    <?php endforeach; ?>

<?php else: ?>
    <span>No templates available</span>
<?php endif; ?>


<?php if ($this->showPhpVersionWizard): ?>
<br />
<br />
    <div class="pul-card pul-card--extended">
        <div class="pul-card__inner">
            <div class="pul-card__body">
                <div class="pul-card__main">
                    <div class="pul-card__main-content">
                        <div>
                            <h3>Warnning!</h3>
                            Your PHP version is not compatible with the next version of app.
                            <br />
                            Please update your PHP version to install new updates
                            <br />
                            <br />
                            <button onclick="openPhpUpgradeWizard()"class="btn action">
                                Click here to upgrade
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<?php else: ?>

<br />
<br />
<?php if ($this->currentVersion != $this->latestVersion): ?>
<a href="<?php echo $this->updateLink; ?>" class="btn action" style="width:200px;">Update</a>
<?php else: ?>
<h3 style="color:green;">Everything is up to date!</h3>
<a href="<?php echo $this->updateLink; ?>" class="btn action" style="width:200px;">Check for updates</a>
<?php endif; ?>

<?php endif; ?>