<?php
/**
 * Microweber auto provision plesk plugin
 * Author: Bozhidar Slaveykov
 * @email: info@microweber.com
 * Copyright: Microweber CMS
 */
?>

<?php echo $this->renderTabs($this->tabs); ?>

<h3><?php echo $this->moduleName; ?> App Version</h3>
<span>Your app version is: </span> <b><?php echo $this->currentVersion; ?></b> <br />
<span>Latest app version is:</span> <b><?php echo $this->latestVersion; ?></b> <br />
<span>Latest app download date:</span> <b><?php echo $this->latestDownloadDate; ?></b><br />
<br />

<?php if ($this->availableTemplates): ?>
    <h3>Available App Templates (<?php echo count($this->availableTemplates); ?>)</h3>
    <?php foreach ($this->availableTemplates as $template): ?>
        <?php echo $template['name']; ?><?php if ($template['version']): ?>(<?php echo $template['version']; ?>)
        <?php endif; ?>, &nbsp;

    <?php endforeach; ?>

<?php else: ?>
    <span>No app templates available</span>
<?php endif; ?>


<?php if ($this->showPhpVersionWizard): ?>
<br />
<br />
    <div class="pul-card pul-card--extended">
        <div class="pul-card__inner">
            <div class="pul-card__body">
                <div class="pul-card__main">
                    <div class="pul-card__main-content">
                        <div>
                            <h3>Warnning!</h3>
                            Your PHP version is not compatible with the next version of <?php echo $this->moduleName; ?>.
                            <br />
                            Please update your PHP version to install new updates
                            <br />
                            <br />
                            <a href="<?php echo $this->phpUpgradeWizardLink; ?>" class="btn action">
                                Click here to upgrade
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


<?php else: ?>

<br />
<br />
<?php if ($this->currentVersion != $this->latestVersion): ?>
<button data-update-link="<?php echo $this->updateLink; ?>" class="btn action js-check-for-update" style="width:200px;">Update</button>
<?php else: ?>
<div class="pul-alert pul-alert--success pul-status-message pul-status-message--success">
<span class="pul-icon pul-status-message__icon">

</span>
    Your app and templates is up-to-date!
</div>
<button data-update-link="<?php echo $this->updateLink; ?>" class="btn action js-check-for-update" style="width:200px;">Check for updates</button>
<?php endif; ?>

<?php if ($this->pluginUpdateLink): ?>
<a href="<?php echo $this->pluginUpdateLink; ?>" class="pul-button" style="width:200px;">Check for plugin updates</a>
<?php endif; ?>

<?php endif; ?>

