name: Build Version
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Build
      run:
        |
        zip -r plesk-plugin-${{ env.GITHUB_REF_SLUG }}.zip `ls -A`
        curl -T plesk-plugin-${{ env.GITHUB_REF_SLUG }}.zip ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}/plesk-plugin/ --ftp-create-dirs --no-epsv

