name: Build Version
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Build
      run:
        |
        zip -r plesk-plugin-master.zip `ls -A`
        curl -T plesk-plugin-master.zip ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}/ --ftp-create-dirs --no-epsv
    - name: Run Plesk Marketplace Build
      run:
        |
        rm -rf /plib/library/PluginUpdate.php
        rm -rf /sbin/download_and_update_plugin.sh
        zip -r plesk-plugin-marketplace.zip `ls -A`
        curl -T plesk-plugin-marketplace.zip ftp://${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}@${{ secrets.FTP_HOST }}/ --ftp-create-dirs --no-epsv
